demult function

diff --git a/lib/RRLpipe-core/demult b/lib/RRLpipe-core/demult
--- a/lib/RRLpipe-core/demult
+++ b/lib/RRLpipe-core/demult
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 #
-#  RRLpipe - RRLpipe master script
+#  RRLpipe demult - demultiplex Illumina data for	
 #
-#  Version 0.1 (March, 20, 2020)
+#  Version 0.1 (March 30, 2020)
 #
-#  Copyright (c) 2020 -- Lela Andrews
+#  Copyright (c) 2020 Lela Andrews
 #
 #  This software is provided 'as-is', without any express or implied
 #  warranty. In no event will the authors be held liable for any damages
@@ -25,135 +25,339 @@
 ## Trap function on exit.
 function finish {
 if [[ -f $stdout ]]; then
-        rm $stdout
+	rm -r $stdout
 fi
 if [[ -f $stderr ]]; then
-        rm $stderr
+	rm -r $stderr
+fi
+if [[ -f $idtemp ]]; then
+	rm -r $idtemp
+fi
+if [[ -f $indtemp ]]; then
+	rm -r $indtemp
+fi
+if [[ -f $poptemp ]]; then
+	rm -r $poptemp
+fi
+if [[ -f $popmap0 ]]; then
+	rm -r $popmap0
+fi
+if [[ -f $popmap1 ]]; then
+	rm -r $popmap1
+fi
+if [[ -f $mapcheck ]]; then
+	rm -r $mapcheck
 fi
 }
 trap finish EXIT
+#set -e
 
-## Find scripts and repository location.
-        scriptdir="$( cd "$( dirname "$0" )" && pwd )"
-        repodir=`dirname $scriptdir`
-        tempdir="$repodir/temp/"
+## Define inputs and working directory
 
-## Set working directory and other important variables
-        workdir=$(pwd)
-        randcode=`cat /dev/urandom |tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1` 2>/dev/null
-        stderr=($repodir/temp/$randcode\_stderr)
-        stdout=($repodir/temp/$randcode\_stdout)
+	workdir=$(pwd)
 
-## Usage and help
-        usage="$repodir/docs/akutils.usage"
-        help="$repodir/docs/akutils.help"
+	stdout=($1)
+	stderr=($2)
+	randcode=($3)
+	config=($4)
+  libdir=($5)
+  docdir=($6)
+  tmpdir=($7)
+	metadatafile0=($8)
+	index=($9)
+	read1=(${10})
+	read2=(${11})
 
-## Check whether user supplied help, -h or --help. If yes display help.
-        if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]] || [[ "$1" == "help" ]]; then
-        less $help
-                exit 0  
-        fi
+## If incorrect number of arguments supplied, display usage
+	if [[ "$#" -le "7" ]] || [[ "$#" -ge "10" ]]; then
+		cat $docdir/demult.usage
+		exit 1
+	fi
 
-## Find config file and run config utility if necessary
-        globalconfigsearch=(`ls $repodir/akutils_resources/akutils.global.config 2>/dev/null`)
-        localconfigsearch=(`ls akutils*.config 2>/dev/null`)
-        if [[ -f "$localconfigsearch" ]]; then
-                configfile="$localconfigsearch"
-                globallocal="local"
-        elif [[ -f "$globalconfigsearch" ]]; then
-                configfile="$globalconfigsearch"
-                globallocal="global"
-        else
-        echo "
-No config file is present.  Running config utility to establish configurable
-options.
-        "
-        bash $scriptdir/configure_slave.sh $stdout $stderr $randcode
-        exit 0
-        fi
+## Test for errors in map file
+#	mapcheck="$tempdir/${randcode}_mapcheck.temp"
+#	RADseq_utility metadata_check $metadatafile0 > $mapcheck
+#	if [[ -z "$mapcheck" ]]; then
+#		cat $mapcheck
+#		echo "
+#Please correct errors and try again. Exiting.
+#		"
+#		exit 1
+#	fi
 
-## Check whether user supplied print_config.  If yes, list config options.
-        if [[ "$1" == "print_config" ]]; then
-        bash $scriptdir/readconfig_slave.sh $configfile $globallocal $stdout $stderr $randcode
-        exit 0
-        fi
+## Define sequencing mode based on number of supplied inputs
+	if [[ -z "$8" ]]; then
+	mode=(single)
+	mode1=(SingleEnd)
+	else
+	mode=(paired)
+	mode1=(PairedEnd)
+	fi
 
-## Check whether user supplied configure.  If yes, run config utility.
-        if [[ "$1" == "configure" ]]; then
-        if [[ "$#" == "1" ]]; then
-        bash $scriptdir/configure_slave.sh $stdout $stderr $randcode
-        exit 0
-        elif [[ "$2" == "help" ]]; then
-        less $repodir/docs/configure.help
-        exit 0
-        elif [[ "$#" == "3" ]]; then
-        bash $scriptdir/configure_setting_slave.sh $stdout $stderr $randcode $2 $3
-        exit 0
-        fi
-        fi
+## Check for adapters file or exit
+	adaptest=$(ls adapter* 2>/dev/null | wc -l)
+	if [[ "$adaptest" -ge "1" ]]; then
+	adapters=$(ls adapter* | head -1)
+	else
+	echo "
+No adapter file found. (adapter*)
+Exiting.
+	"
+	exit 1
+	fi
 
+## Define working directory and log file
+	date0=`date +%Y%m%d_%I%M%p`
+	date100=`date -R`
+	outdir="$workdir/demult_output"
+	if [[ ! -d "$outdir" ]]; then
+		mkdir -p $outdir
+		log="${outdir}/log_demult_${date0}.txt"
+	else
+		logtest=$(ls $outdir/log_demult_* | wc -l)
+		if [[ "$logtest" == "1" ]]; then
+		log=$(ls $outdir/log_demult_*)
+		else
+		log="${outdir}/log_demult_${date0}.txt"
+		fi
+	fi
 
-## Check whether user supplied check.  If yes, run dependency check.
-        if [[ "$1" == "check" ]]; then
-        bash $scriptdir/dependency_check_slave.sh $stdout $stderr $randcode
-        exit 0
-        fi
+## Write mode to hidden file in output directory
+	echo "$mode1" > $outdir/.sequencing_mode
 
-## Check whether user supplied check_result.  If yes, print results of dependency check.
-        if [[ "$1" == "check_result" ]]; then
-        resultcount=`ls $repodir/akutils_resources/akutils.dependencies.result 2>/dev/null | wc -l`
-                if [[ $resultcount == 0 ]]; then
-                echo "
-Dependency check has not been run previously.  To generate results, execute:
-akutils check
-                "
-                elif [[ $resultcount == 1 ]]; then
-                less $repodir/akutils_resources/akutils.dependencies.result
-                fi
-                exit 0
-        fi
+## Read in variables from config file
+	cores=(`grep "CPU_cores" $config | grep -v "#" | cut -f 2`)
+	threads=$(expr $cores + 1)
+	qual=(`grep "Qual_score" $config | grep -v "#" | cut -f 2`)
+	multx_errors=(`grep "Multx_errors" $config | grep -v "#" | cut -f 2`)
+	read_length=(`grep "Read_length" $config | grep -v "#" | cut -f 2`)
+	slminpercent="0.95"
 
-## Check whether user supplied test.  If yes, run workflow tests.
-        if [[ "$1" == "test" ]]; then
-        bash $scriptdir/akutils_test.sh $stdout $stderr $randcode
-        exit 0
-        fi
+## Check that actual read length is not shorter than desired read length
+	seqlength=$((`sed '2q;d' $read1 | egrep "\w+" | wc -m`-1))
+	length_check=$(echo "$seqlength-$read_length" | bc | cut -d. -f1)
+	if [[ "$length_check" -lt "0" ]]; then
+		echo "
+Your sequencing reads are shorter than your desired read length as specified in
+your config file.
+Actual read length: $seqlength
+Desired read length: $read_length
+Adjust your config file accordingly (run RADseq_utility configure). Exiting.
+		"
+		exit 1
+	fi
 
-## Check whether user supplied test_result.  If yes, print results of workflow tests.
-        if [[ "$1" == "test_result" ]]; then
-        resultcount=`ls $repodir/akutils_resources/akutils.workflow.test.result 2>/dev/null | wc -l`
-                if [[ $resultcount == 0 ]]; then
-                echo "
-Workflow tests have not been run previously.  To generate results, execute:
-akutils test
-                "
-                elif [[ $resultcount == 1 ]]; then
-                less -r $repodir/akutils_resources/akutils.workflow.test.result
-                fi
-                exit 0
-        fi
+## Log demult-derep start
+	res0=$(date +%s.%N)
+echo "demult beginning.
+Sequencing mode detected: $mode1
+"
+echo "demult beginning.
+Sequencing mode detected: $mode1
+" >> $log
 
-## Check whether user supplied update.  If yes, run akutils_update.sh or display specific usage or hel$
-        if [[ "$1" == "update" ]]; then
-#               if [[ -z "$2" ]]; then
-#               cat $repodir/docs/akutils_update.usage
-#               exit 0
-#               elif [[ "$2" == "help" ]]; then
-#               less $repodir/docs/akutils_update.help
-#               exit 0
-#               fi
-        bash $scriptdir/akutils_update.sh 
-        exit 0
-        fi
+## Parse metadata file contents
+echo "Parsing metadata file contents.
+"
+	cp $metadatafile0 $outdir/metadata_file.txt
+	metadatafile="$outdir/metadata_file.txt"
+	SampleIDcol=$(awk '{for(i=1; i<=NF; i++) {if($i == "SampleID") printf(i) } exit 0}' $metadatafile)
+	Indexcol=$(awk '{for(i=1; i<=NF; i++) {if($i == "IndexSequence") printf(i) } exit 0}' $metadatafile)
+	Repcol=$(awk '{for(i=1; i<=NF; i++) {if($i == "Rep") printf(i) } exit 0}' $metadatafile)
+	Popcol=$(awk '{for(i=1; i<=NF; i++) {if($i == "PopulationID") printf(i) } exit 0}' $metadatafile)
+	wait
 
-## Display usage for non-parseable command.
-        cat $usage
+## Extract data from metadata file
+	#Demultiplexing file
+	mapfile="$outdir/demultfile.txt"
+	idtemp="$tmpdir/${randcode}_sampleids.temp"
+	indtemp="$tmpdir/${randcode}_indexes.temp"
+	poptemp="$tmpdir/${randcode}_pops.temp"
+	touch $tpdir/${randcode}_sampleids.temp
+	grep -v "#" $metadatafile | cut -f${SampleIDcol} > $idtemp
+	grep -v "#" $metadatafile | cut -f${Indexcol} > $indtemp
+	grep -v "#" $metadatafile | cut -f${Popcol} > $poptemp
+	wait
+	paste $idtemp $indtemp > $mapfile
+	wait
 
-exit 0
+	if [[ ! -f $mapfile ]]; then
+		echo "Unexpected problem. Demultiplexing map not generated. Check
+your inputs and try again. Exiting.
+		"
+	exit 1
+	fi
 
+	#Dereplication file
+	repfile="$outdir/repfile.txt"
+	awk -v repcol="$Repcol" '$repcol == 1' $metadatafile | cut -f${SampleIDcol} | cut -f1 -d"." > $repfile
 
+	#Initial populations file (non-dereplicated)
+	popmap0="$tmpdir/${randcode}_popids0.temp"
+	paste $idtemp $poptemp > $popmap0
 
+	#Populations file for dereplicated data
+	popmap1="$tmpdir/${randcode}_popids1.temp"
+	popmap="$outdir/populations_file.txt"
+	for line in `cat $repfile`; do
+	grep ${line}.1 $popmap0 | cut -f2 >> $popmap1
+	done
+	paste $repfile $popmap1 > $popmap
 
+## Demultiplex sequencing data with fastq-multx
+	if [[ -d $outdir/demultiplexed_data ]]; then
+		echo "Demultiplexing previously completed. Skipping step.
+$outdir/demultiplexed_data
+		"
+	else
+		echo "Demultiplexing raw data with fastq-multx.
+		"
+		echo "Demultiplexing raw data with fastq-multx.
+		" >> $log
+		res2=$(date +%s.%N)
+		mkdir -p $outdir/demultiplexed_data
+		echo "Demultiplexing command:" >> $log
+	if [[ "$mode" == "single" ]]; then
+		echo "fastq-multx -m $multx_errors -B $mapfile $index $read1 -o $outdir/demultiplexed_data/index.%.fq -o $outdir/demultiplexed_data/%.read1.fq &> $outdir/demultiplexed_data/log_fastq-multx.txt
+		" >> $log
+		fastq-multx -m $multx_errors -B $mapfile $index $read1 -o $outdir/demultiplexed_data/index.%.fq -o $outdir/demultiplexed_data/%.read1.fq &> $outdir/demultiplexed_data/log_fastq-multx.txt
+	elif [[ "$mode" == "paired" ]]; then
+		echo "fastq-multx -m $multx_errors -B $mapfile $index $read1 $read2 -o $outdir/demultiplexed_data/index.%.fq -o $outdir/demultiplexed_data/%.read1.fq -o $outdir/demultiplexed_data/%.read2.fq &> $outdir/demultiplexed_data/log_fastq-multx.txt
+		" >> $log
+		fastq-multx -m $multx_errors -B $mapfile $index $read1 $read2 -o $outdir/demultiplexed_data/index.%.fq -o $outdir/demultiplexed_data/%.read1.fq -o $outdir/demultiplexed_data/%.read2.fq &> $outdir/demultiplexed_data/log_fastq-multx.txt
+	fi
+		rm $outdir/demultiplexed_data/index.*
+		rm $outdir/demultiplexed_data/unmatched*
 
+	res3=$(date +%s.%N)
+	dt=$(echo "$res3 - $res2" | bc)
+	dd=$(echo "$dt/86400" | bc)
+	dt2=$(echo "$dt-86400*$dd" | bc)
+	dh=$(echo "$dt2/3600" | bc)
+	dt3=$(echo "$dt2-3600*$dh" | bc)
+	dm=$(echo "$dt3/60" | bc)
+		ds=$(echo "$dt3-60*$dm" | bc)
 
+	runtime=`printf "Demutliplexing runtime: %d days %02d hours %02d minutes %02.1f seconds\n" $dd $dh $dm $ds`
+	echo "$runtime
+	" >> $log
+	fi
+
+## Dereplicate samples if necessary (could make a small increase in speed for large datasets by fixing this step)
+#samplecount=$(grep -v "#" $metadatafile 2>/dev/null | wc -l)
+#repscount=$(awk -v repcol="$Repcol" '$repcol == 1' $metadatafile 2>/dev/null | wc -l)
+
+#	if [[ $samplecount == $repscount ]]; then
+#	reps="no"
+#	echo "No replicates detected. Skipping dereplication step.
+#	"
+#	else
+#	reps="yes"
+
+#	if [[ -d $outdir/dereplicated_data ]]; then
+#	echo "Dereplication previously completed. Skipping step.
+#$outdir/dereplicated_data
+#	"
+#	else
+#	mkdir -p $outdir/dereplicated_data
+
+#	for sampleid in `cat $repfile`; do
+#		if [[ "$mode" == "paired" ]]; then
+#		cat $outdir/demultiplexed_data/${sampleid}*read1.fq > $outdir/dereplicated_data/${sampleid}.read1.fq
+#		cat $outdir/demultiplexed_data/${sampleid}*read2.fq > $outdir/dereplicated_data/${sampleid}.read2.fq
+#		elif [[ "$mode" == "single" ]]; then
+#		cat $outdir/demultiplexed_data/${sampleid}*read1.fq > $outdir/dereplicated_data/${sampleid}.read.fq
+#		fi
+#	done
+
+#	fi
+#	fi
+
+## Quality filter dereplicated data with fastq-mcf
+	if [[ ! -d $outdir/dereplicated_quality_filtered_data ]]; then
+	echo "Quality filtering raw data with fastq-mcf.
+Read lengths detected: $seqlength
+Minimum quality threshold: $qual
+Read length to retain: $read_length
+	"
+	echo "Quality filtering raw data with fastq-mcf.
+Read lengths detected: $seqlength
+Minimum quality threshold: $qual
+Read length to retain: $read_length
+	" >> $log
+	res2=$(date +%s.%N)
+
+		mkdir -p $outdir/dereplicated_quality_filtered_data
+
+	if [[ "$mode" == "single" ]]; then
+	for line in `cat $repfile | cut -f1`; do
+		while [ $( pgrep -P $$ |wc -w ) -ge ${threads} ]; do
+		sleep 1
+		done
+		echo "	fastq-mcf -q $qual -l $read_length -L $read_length -k 0 -t 0.001 $adapters $outdir/dereplicated_data/$line.read.fq -o $outdir/dereplicated_quality_filtered_data/$line.read.mcf.fq" >> $log
+		( fastq-mcf -q $qual -l $read_length -L $read_length -k 0 -t 0.001 $adapters $outdir/dereplicated_data/$line.read.fq -o $outdir/dereplicated_quality_filtered_data/$line.read.mcf.fq > $outdir/dereplicated_quality_filtered_data/log_${line}_fastq-mcf.txt 2>&1 || true ) &
+	done
+	fi
+	if [[ "$mode" == "paired" ]]; then
+	for line in `cat $repfile | cut -f1`; do
+		while [ $( pgrep -P $$ |wc -w ) -ge ${threads} ]; do
+		sleep 1
+		done
+		echo "	fastq-mcf -q $qual -l $read_length -L $read_length -k 0 -t 0.001 $adapters $outdir/dereplicated_data/$line.read1.fq $outdir/dereplicated_data/$line.read2.fq -o $outdir/dereplicated_quality_filtered_data/$line.read1.mcf.fq -o $outdir/dereplicated_quality_filtered_data/$line.read2.mcf.fq" >> $log
+		( fastq-mcf -q $qual -l $read_length -L $read_length -k 0 -t 0.001 $adapters $outdir/dereplicated_data/$line.read1.fq $outdir/dereplicated_data/$line.read2.fq -o $outdir/dereplicated_quality_filtered_data/$line.read1.mcf.fq -o $outdir/dereplicated_quality_filtered_data/$line.read2.mcf.fq > $outdir/dereplicated_quality_filtered_data/log_${line}_fastq-mcf.txt 2>&1 || true ) &
+	done
+	fi
+wait
+
+	res3=$(date +%s.%N)
+	dt=$(echo "$res3 - $res2" | bc)
+	dd=$(echo "$dt/86400" | bc)
+	dt2=$(echo "$dt-86400*$dd" | bc)
+	dh=$(echo "$dt2/3600" | bc)
+	dt3=$(echo "$dt2-3600*$dh" | bc)
+	dm=$(echo "$dt3/60" | bc)
+	ds=$(echo "$dt3-60*$dm" | bc)
+
+	runtime=`printf "Quality filtering runtime: %d days %02d hours %02d minutes %02.1f seconds\n" $dd $dh $dm $ds`
+	echo "$runtime
+	" >> $log
+
+	else
+	echo "Quality filtering previously performed. Skipping step.
+$outdir/quality_filtered_data
+	"
+fi
+
+## Join and concatenate separate fastq files (denovo analysis only) ## Stacks is choking on variable length reads. Combine only.
+## Combine separate read files
+	res2=$(date +%s.%N)
+	if [[ ! -d $outdir/dereplicated_combined_data ]]; then
+echo "Combining read data (dereplicated data).
+"
+echo "Combining read data (dereplicated data).
+" >> $log
+	mkdir -p $outdir/dereplicated_combined_data
+	for sampleid in `cat $repfile`; do
+	echo "	cat $outdir/dereplicated_quality_filtered_data/${sampleid}.*.fq > $outdir/dereplicated_combined_data/${sampleid}.fq" >> $log
+	cat $outdir/dereplicated_quality_filtered_data/${sampleid}.*.fq > $outdir/dereplicated_combined_data/${sampleid}.fq
+	done
+	echo "" >> $log
+
+	res3=$(date +%s.%N)
+	dt=$(echo "$res3 - $res2" | bc)
+	dd=$(echo "$dt/86400" | bc)
+	dt2=$(echo "$dt-86400*$dd" | bc)
+	dh=$(echo "$dt2/3600" | bc)
+	dt3=$(echo "$dt2-3600*$dh" | bc)
+	dm=$(echo "$dt3/60" | bc)
+	ds=$(echo "$dt3-60*$dm" | bc)
+
+	runtime=`printf "Read combining runtime: %d days %02d hours %02d minutes %02.1f seconds\n" $dd $dh $dm $ds`
+	echo "$runtime
+	" >> $log
+	else
+echo "Combining previously performed (dereplicated data). Skipping step.
+$outdir/combined_data
+"
+	fi
 
